name: CI-build-and-push-image-for-dotnetapp

on:
  # Trigger the workflow when code is pushed to the feature branch
  push:
    branches:
      - feature/initial-implementation
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  # Trigger the workflow when a pull request is made to the feature branch
  pull_request:
    branches:
      - feature/initial-implementation
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using the credentials you stored in GitHub Secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dotnetapp:latest, ${{ secrets.DOCKERHUB_USERNAME }}/dotnetapp:${{ github.run_number }}
